"""Tests for apcore_toolkit.output.yaml_writer — YAMLWriter."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from apcore_toolkit.output.types import WriteResult
from apcore_toolkit.output.yaml_writer import YAMLWriter
from apcore_toolkit.types import ScannedModule


class TestYAMLWriterDryRun:
    def setup_method(self) -> None:
        self.writer = YAMLWriter()

    def test_empty_modules(self) -> None:
        result = self.writer.write([], "/tmp/out", dry_run=True)
        assert result == []

    def test_single_module(self, sample_module: ScannedModule) -> None:
        result = self.writer.write([sample_module], "/tmp/out", dry_run=True)
        assert len(result) == 1
        assert isinstance(result[0], WriteResult)
        assert result[0].module_id == "users.get_user"
        assert result[0].verified is True

    def test_multiple_modules(self, sample_module: ScannedModule, annotated_module: ScannedModule) -> None:
        result = self.writer.write([sample_module, annotated_module], "/tmp/out", dry_run=True)
        assert len(result) == 2


class TestYAMLWriterFileOutput:
    def setup_method(self) -> None:
        self.writer = YAMLWriter()

    def test_writes_files(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        results = self.writer.write([sample_module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1
        content = files[0].read_text()
        assert "Auto-generated by apcore-toolkit scanner" in content
        parsed = yaml.safe_load(content)
        assert parsed["bindings"][0]["module_id"] == "users.get_user"
        assert len(results) == 1
        assert results[0].path is not None

    def test_atomic_write_leaves_no_tmp_files(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        """Atomic write: a successful write must leave no ``.tmp`` residue.

        Regression for non-atomic write that used ``Path.write_text`` directly.
        The new implementation writes to ``<name>.<pid>.tmp`` then
        ``os.replace()`` onto the final path; after success no tmp should
        remain.
        """
        self.writer.write([sample_module], str(tmp_path))
        tmp_files = list(tmp_path.glob("*.tmp"))
        assert tmp_files == []

    def test_write_skips_symlink_target(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        """Writer must refuse to overwrite a symlink at the final target path.

        A symlink at the target could redirect the write outside the output
        directory even when the resolved parent looks safe.
        """
        import re as _re

        safe_id = _re.sub(r"[^a-zA-Z0-9._-]", "_", sample_module.module_id)
        safe_id = _re.sub(r"\.{2,}", "_", safe_id)
        target_name = f"{safe_id}.binding.yaml"
        target = tmp_path / target_name
        decoy = tmp_path / "decoy.txt"
        decoy.write_text("should not be overwritten", encoding="utf-8")
        target.symlink_to(decoy)

        results = self.writer.write([sample_module], str(tmp_path))

        assert len(results) == 1
        assert results[0].verified is False
        assert results[0].verification_error is not None
        assert "symlink" in results[0].verification_error.lower()
        assert decoy.read_text(encoding="utf-8") == "should not be overwritten"

    def test_atomic_write_cleans_tmp_on_failure(
        self, tmp_path: Path, sample_module: ScannedModule, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When ``os.replace`` fails, the tmp file must not be left behind."""
        from apcore_toolkit.output import yaml_writer as _yw

        def _boom(_src: str, _dst: str) -> None:
            raise OSError("simulated rename failure")

        monkeypatch.setattr(_yw.os, "replace", _boom)
        from apcore_toolkit.output.errors import WriteError

        with pytest.raises(WriteError):
            self.writer.write([sample_module], str(tmp_path))

        tmp_files = list(tmp_path.glob("*.tmp"))
        assert tmp_files == []

    def test_creates_output_dir(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        out_dir = tmp_path / "nested" / "output"
        self.writer.write([sample_module], str(out_dir))
        assert out_dir.exists()
        assert len(list(out_dir.glob("*.binding.yaml"))) == 1

    def test_filename_sanitization(self, tmp_path: Path) -> None:
        module = ScannedModule(
            module_id="weird/id..test",
            description="test",
            input_schema={},
            output_schema={},
            tags=[],
            target="m:f",
        )
        self.writer.write([module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1
        # Slashes replaced, double-dots collapsed
        filename = files[0].name
        assert "/" not in filename
        assert ".." not in filename

    def test_overwrite_existing(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        self.writer.write([sample_module], str(tmp_path))
        self.writer.write([sample_module], str(tmp_path))
        files = list(tmp_path.glob("*.binding.yaml"))
        assert len(files) == 1

    def test_none_annotations_in_output(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        result = self.writer.write([sample_module], str(tmp_path), dry_run=True)
        assert len(result) == 1
        assert result[0].module_id == "users.get_user"

    def test_binding_contains_all_fields(self, annotated_module: ScannedModule) -> None:
        """Verify binding dict still has all fields (via dry_run + _build_binding)."""
        writer = YAMLWriter()
        binding = writer._build_binding(annotated_module)
        assert binding["spec_version"] == "1.0"
        b = binding["bindings"][0]
        assert b["module_id"] == "tasks.create_task"
        assert b["target"] == "myapp.views:create_task"
        assert b["description"] == "Create a new task"
        assert b["documentation"] == "Create a new task with the given title."
        assert b["tags"] == ["tasks"]
        assert b["version"] == "2.0.0"
        assert b["annotations"]["destructive"] is True
        assert b["metadata"]["http_method"] == "POST"

    def test_binding_omits_display_when_none(self, sample_module: ScannedModule) -> None:
        """display is None by default and should be absent from YAML output."""
        writer = YAMLWriter()
        binding = writer._build_binding(sample_module)
        assert "display" not in binding["bindings"][0]

    def test_binding_emits_display_when_set(self, sample_module: ScannedModule) -> None:
        """display overlay should round-trip through YAML when set."""
        import dataclasses as _dc

        mod = _dc.replace(sample_module, display={"mcp": {"alias": "users_get"}, "alias": "users.get"})
        writer = YAMLWriter()
        binding = writer._build_binding(mod)
        assert binding["bindings"][0]["display"] == {
            "mcp": {"alias": "users_get"},
            "alias": "users.get",
        }


class TestYAMLWriterVerification:
    def setup_method(self) -> None:
        self.writer = YAMLWriter()

    def test_verify_valid_file(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        results = self.writer.write([sample_module], str(tmp_path), verify=True)
        assert len(results) == 1
        assert results[0].verified is True
        assert results[0].verification_error is None
        assert results[0].path is not None

    def test_verify_detects_corrupted_yaml(self, tmp_path: Path, sample_module: ScannedModule) -> None:
        # Write normally first
        results = self.writer.write([sample_module], str(tmp_path))
        file_path = Path(results[0].path)

        # Corrupt the file
        file_path.write_text("{{invalid yaml: [", encoding="utf-8")

        # Verify directly
        result = WriteResult(module_id="users.get_user", path=str(file_path))
        verified = YAMLWriter._verify(result, file_path)
        assert verified.verified is False
        assert "Invalid YAML" in verified.verification_error

    def test_verify_detects_missing_bindings(self, tmp_path: Path) -> None:
        file_path = tmp_path / "test.binding.yaml"
        file_path.write_text("some_key: value\n", encoding="utf-8")

        result = WriteResult(module_id="test", path=str(file_path))
        verified = YAMLWriter._verify(result, file_path)
        assert verified.verified is False
        assert "bindings" in verified.verification_error

    def test_verify_detects_missing_module_id(self, tmp_path: Path) -> None:
        file_path = tmp_path / "test.binding.yaml"
        file_path.write_text("bindings:\n  - target: m:f\n", encoding="utf-8")

        result = WriteResult(module_id="test", path=str(file_path))
        verified = YAMLWriter._verify(result, file_path)
        assert verified.verified is False
        assert "module_id" in verified.verification_error

    def test_verify_not_run_in_dry_run(self, sample_module: ScannedModule) -> None:
        results = self.writer.write([sample_module], "/tmp/out", dry_run=True, verify=True)
        assert len(results) == 1
        # dry_run skips verification, defaults to verified=True
        assert results[0].verified is True
